# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: LastThreeLTS

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
 schedule:
   - cron: 0 6 1 * *
 watch:
   types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: System info
      run: |
           cat /proc/cpuinfo
           cat /proc/meminfo
           df -h
           du -hd1

    - name: Get current date  
      id: date  
      run: echo "::set-output name=date::$(date +'%Y%m%d')" 
          
    - uses: actions/checkout@v3
    
    - name: Download node-gyp
      run: |
           cd Node.js
           npm install
           node index.js -p win32 -a x64 -alc 3
           node index.js -p linux -a x64 -alc 3
           node index.js -p linux -a arm64 -alc 3
           node index.js -p linux -a armv7l -alc 3
           find . -maxdepth 1 -type d -name "node-gyp-offline-install*" | xargs -i tar zcvf {}.tar.gz {}
           ls
           cp -rf *.tar.gz /opt
          
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: AtuoBuild_${{steps.date.outputs.date}}
          prerelease: false
          title: AtuoBuild_${{steps.date.outputs.date}}
          files: |
            /opt/*.tar.gz
